name: cashee
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management, navigation and miscellaneous
  get: 4.6.5

  # Local storage
  get_storage: ^2.0.3

  # Localization package
  easy_localization: 3.0.1

  # Fonts and Styles
  google_fonts: 3.0.1

  # Handle Svg images
  flutter_svg: ^1.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - lib/assets/translations/
    - lib/assets/icons/
